okta:
  oauth2:
    issuer: https://dev-19929343.okta.com/oauth2/default
    client-id: 0oa4mrgnlzN0vRZHB5d7
    # typically, never show secret but only have it here for demonstration purposes
    client-secret: 5lask3vA3B6Tangj_LHFtdo2cGqNIhuI6NTLwpxs
