
spring:
  application:
    name: api-gateway-service
  security:
    user:
      name: test-user
      password: password

server:
  port: 8080
  servlet:
    context-path: /services

zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie
  routes:
    messaging-service-client:
      path: /messaging/**
      url: http://localhost:8090/messaging
