
spring:
  application:
    name: api-gateway-service

server:
  port: 8080
  servlet:
    context-path: /service

zuul:
  routes:
    messaging-service-client:
      path: /messaging/**
      url: http://localhost:8090/messaging


#okta:
#  oauth2:
#    issuer: https://dev-19929343.okta.com/oauth2/default
#    client-id: 0oa4mrgnlzN0vRZHB5d7
#    # typically, never show secret but only have it here for demonstration purposes
#    client-secret: 5lask3vA3B6Tangj_LHFtdo2cGqNIhuI6NTLwpxs
